openapi: 3.0.3
info:
  title: Notification Center Reception API
  version: 1.0.0
  description: API para mandar notificaciones de diferentes canales (EMAIL, SMS, PUSH) al Notification Center
  servers:
    - url: http://localhost:8080/api
  paths:
    /onboarding:
      post:
        summary: Subscibcion al Notification Center
        description: Endpoint para que los servicios se suscriban al Notification Center y puedan enviar notificaciones
        operationId: subscribeToNotificationCenter
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnboardingRequest'
        responses:
          '201':
            description: Cliente suscrito exitosamente
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/OnboardingResponse'
    /send:
      post:
        summary: Enviar notificación al Notification Center
        description: Endpoint para enviar una notificación al Notification Center
        operationId: sendNotificationToCenter
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendNotificationRequest'
        responses:
          '200':
            description: Notificación enviada exitosamente
    /resend:
      post:
        summary: Reenviar notificación al Notification Center
        description: Endpoint para reenviar una notificación al Notification Center
        operationId: resendNotificationToCenter
        parameters:
          - in: query
            name: notificationId
            schema:
              type: string
              format: uuid
            required: true
            description: ID de la notificación a reenviar
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendNotificationRequest'
        responses:
          '200':
            description: Notificación enviada exitosamente
      get:
        summary: Obtener notificaciones pendientes de reenvío
        description: Endpoint para obtener las notificaciones han sido programadas para reenvío pero aún no han sido reenviadas
        operationId: getResendNotifications
        responses:
          '200':
            description: Lista de notificaciones pendientes de reenvío
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/ResendedNotificationResponse'
    /notificaciones:
      get:
        summary: Obtener notificaciones enviadas por un servicio
        description: Endpoint para obtener las notificaciones que un servicio ha enviado al Notification Center
        operationId: getSentNotifications
        parameters:
          - in: query
            name: apiKey
            schema:
              type: string
              format: uuid
            required: true
            description: API Key del servicio para filtrar las notificaciones enviadas por ese servicio
        responses:
          '200':
            description: Lista de notificaciones enviadas por el servicio
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/SentNotificationResponse'
components:
  schemas:
    OnboardingRequest:
      type: object
      required:
        - nombreServicio
        - correoContacto
        - telefonoContacto
      properties:
        nombreServicio:
          type: string
          example: Adondevamos.net
        correoContacto:
          type: string
          example: contacto@adondevamos.net
        telefonoContacto:
          type: string
          example: "+1234567890"
    OnboardingResponse:
      type: object
      required:
        - ApiKey
        - status
      properties:
        ApiKey:
          type: string
          format: uuid
        status:
          type: string
          example: SUBSCRIBED
